name: Crypto algorithm testing pipeline

on:
  push:
    branches: [ "crypto-test" ]
  pull_request:
    branches: [ "crypto-test" ]
  workflow_dispatch:

jobs:
  crypto_testing_job:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: build kernel & modules
      run: |
        cp config-um .config
        make olddefconfig ARCH=um
        make ARCH=um all
        mkdir initramfs
        make modules_install INSTALL_MOD_PATH=./initramfs ARCH=um
    - name: prepare initramfs
      run: |
        sudo apt-get install busybox-static
        mkdir initramfs/bin
        cp -p /bin/busybox initramfs/bin/busybox
        cp -p zeta/init  initramfs/init
        cp -p zeta/test-script.sh initramfs/test-script.sh
        cd initramfs
        find . -print0 | cpio --null --create --verbose --format=newc | gzip --best > ../uml-initramfs.cpio.gz
        cd ..
    - name: run user-mode linux test harness
      run: |
        sudo ./linux initrd=uml-initramfs.cpio.gz > tcrypt.out 2>&1
      shell: bash
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1