name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: move config
      run: cp config-um .config
    - name: make
      run: make ARCH=um all
    - name: create artifacts dir
      run: mkdir artifacts
    - name: copy kernel
      run: cp linux artifacts/
    - name: copy kernel modules
      run: make modules_install INSTALL_MOD_PATH=./artifacts ARCH=um
    - name: remove kernel module directory simlinks
      run: rm artifacts/lib/modules/$(make kernelrelease)/build artifacts/lib/modules/$(make kernelrelease)/source
    - uses: actions/upload-artifact@v3
      with:
        name: linux-build-artifacts
        path: artifacts/
